### ISSUE TITLE
No predefined scripts for starting app

### ISSUE THREAD

**Issue by michaelBenin** [strongloop/loopback-example-mongodb#1]
https://github.com/strongloop/loopback-example-mongodb/blob/master/package.json#L6

**Comment by superkhau** [comment]
Would you like to submit a PR?

**Comment by ackuser** [comment]
I am not sure what you want to achieve, but you can start the app with something like:

### For StrongLoop Arc run:

```javascript
slc arc
```
and 

### For Browse your REST API run: 

```javascript
node .
```

**Comment by superkhau** [comment]
Fixed at #5. Closing.
