### ISSUE TITLE
loopback deprecations

### ISSUE THREAD

**Issue by michaelBenin** [strongloop/loopback-example-mongodb#2]
loopback deprecated Routes "/methods" and "/models" are considered dangerous and should not be used.
Disable them by setting "legacyExplorer=false" in "server/config.json" or via "app.set()". node_modules/loopback/node_modules/express/lib/router/layer.js:82:5

**Comment by superkhau** [comment]
What version of loopback are you using? This was fixed in v2.14.0 I believe. Anyways, marking as duplicate. Reopen if you still think its valid.

See https://github.com/strongloop/loopback/issues/1134
